
portrait = [
    "Photorealistic portrait",
    "Photorealistic headshot",
    "Classic Portrait",
    "Candid Portrait",
    "Environmental Portrait",
    "Studio Portrait",
    "Headshot",
    "Close-up Portrait",
    "Fashion Portrait",
    "Glamour Portrait",
    "Lifestyle Portrait",
    "Fine Art Portrait",
    "Documentary Portrait",
    "Surreal Portrait",
    "Dramatic Portrait",
    "Minimalist Portrait",
    "Moody Portrait",
    "Character Portrait",
    "Head and Shoulders Portrait",
    "Three-Quarter Portrait",
    "Full-Length Portrait",
    "High-Angle Portrait",
    "Low-Angle Portrait",
    "Profile Portrait",
    "Silhouette Portrait",
    "High-Key Portrait",
    "Low-Key Portrait",
    "Rembrandt Portrait",
    "Split Lighting Portrait",
    "Loop Lighting Portrait",
    "Broad Lighting Portrait",
    "Short Lighting Portrait",
    "Glamour Lighting Portrait",
    "Beauty Lighting Portrait",
    "Window Light Portrait",
    "Natural Light Portrait",
    "Outdoor Portrait",
    "Indoor Portrait",
    "Wildlife Portrait",
    "Soulful Portrait",
    "Emotive Portrait",
    "Expressive Portrait",
    "Intimate Portrait",
    "Candid Portrait",
    "Character Portrait",
    "Environmental Portrait",
    "Lifestyle Portrait",
]

colors = [
    "Red",
    "Green",
    "Blue",
    "Yellow",
    "Orange",
    "Purple",
    "Pink",
    "Brown",
    "White",
    "Black",
    "Gray",
    "Crimson",
    "Scarlet",
    "Ruby",
    "Cherry",
    "Burgundy",
    "Maroon",
    "Coral",
    "Vermilion",
    "Raspberry",
    "Firebrick",
    "Emerald",
    "Lime",
    "Olive",
    "Jade",
    "Mint",
    "Chartreuse",
    "Forest Green",
    "Sage",
    "Fern Green",
    "Teal",
    "Sapphire",
    "Sky Blue",
    "Navy Blue",
    "Turquoise",
    "Cobalt Blue",
    "Baby Blue",
    "Steel Blue",
    "Azure",
    "Indigo",
    "Cerulean",
    "Lemon",
    "Gold",
    "Mustard",
    "Amber",
    "Honey",
    "Dandelion",
    "Cream",
    "Yellow Ochre",
    "Buttercup",
    "Saffron",
    "Tangerine",
    "Peach",
    "Apricot",
    "Coral",
    "Burnt Orange",
    "Pumpkin",
    "Terracotta",
    "Rust",
    "Carrot",
    "Ginger",
    "Lavender",
    "Violet",
    "Lilac",
    "Plum",
    "Mauve",
    "Orchid",
    "Amethyst",
    "Grape",
    "Eggplant",
    "Royal Purple",
    "Blush",
    "Bubblegum",
    "Fuchsia",
    "Rose",
    "Salmon",
    "Coral Pink",
    "Hot Pink",
    "Orchid Pink",
    "Magenta",
    "Carnation",
    "Tan",
    "Beige",
    "Chocolate",
    "Caramel",
    "Coffee",
    "Chestnut",
    "Mahogany",
    "Auburn",
    "Walnut",
    "Sienna",
    "Ivory",
    "Pearl",
    "Silver",
    "Gold",
    "Platinum",
    "Bronze",
    "Copper",
    "Mercury",
    "Onyx",
    "Opal"
]

lighting = [
    "Natural Light",
    "Soft Light",
    "Hard Light",
    "Diffused Light",
    "Backlighting",
    "Low Key Lighting",
    "High Key Lighting",
    "Side Lighting",
    "Top Lighting",
    "Rim Lighting",
    "Rembrandt Lighting",
    "Split Lighting",
    "Silhouette Lighting",
    "Candlelight",
    "Firelight",
    "Moonlight",
    "Sunlight",
    "Moonlight",
    "Golden Hour",
]


camera_settings_and_types = ['Aperture Priority Mode', 'Shutter Priority Mode', 'Manual Mode', 'Portrait Mode', '50mm Prime Lens', '85mm Prime Lens', 'Telephoto Lens', 'Wide-Angle Lens', 'Full Frame Camera',
                             'Crop Sensor Camera', 'Natural Light', 'Studio Lighting', 'Softbox', 'Beauty Dish', 'Fill Light', 'Reflector', 'Bokeh', 'Shallow Depth of Field', 'ISO 100', 'ISO 200', 'ISO 400', 'Low ISO', 'Medium ISO', 'High ISO']

illustrators = ['Ciruelo Cabral', 'Omar Rayyan', 'Allen Williams', 'Mélanie Delon', 'Rebecca Yanovskaya', "Tomer Hanuka", "James Jean", "Yuko Shimizu", "Sam Wolfe Connelly", "Yoshitaka Amano", "J.A.W. Cooper", "Audrey Kawasaki",
                "Esao Andrews", "Nico Delort", "Beeple", "Loish", "Feng Zhu", "Craig Mullins", "Sachin Teng", "Simon Stålenhag", "Jama Jurabaev", "Pascal Campion", "WLOP", "Nivanh Chanthara", "Marta Nael", "Ross Tran", "Ilya Kuvshinov", "Sparth"]

artists_and_photographers = ['Gerald Brom', 'Kinuko Y. Craft', 'Charles Vess', 'Ruth Sanderson', 'Stephanie Law', 'Bastien Lecouffe Deharme', 'Anna Dittmann', 'Donato Arts', 'Kerem Beyit', 'Victoria Frances', 'Michael Komarck', 'Donato Giancola', 'Todd Lockwood', 'Kekai Kotaki', 'Wayne Reynolds', 'Cynthia Sheppard', 'Jesper Ejsing', 'Luis Royo', 'Boris Vallejo', 'Frank Frazetta', 'H.R. Giger', 'Brian Froud', 'Nekro', 'Jenny Dolfen', 'Tommy Arnold', 'Magali Villeneuve', 'Rob Alexander', 'Mark Zug', 'Larry Elmore', 'Tony DiTerlizzi',
                             'Viktor Titov', 'Anne Stokes', 'Keith Parkinson', 'Jessica Rossier', 'Elena Dudina', 'Ben Wootten', 'Amanda Diaz', 'Lara Jade', 'Annie Leibovitz', 'Gregory Crewdson', 'Erik Almas', 'Justin Gerard', 'Mona Finden', 'Rovina Cai', 'Kari Christensen', 'Howard Lyon', 'Noah Bradley', 'Julie Dillon', 'Rebecca Guay', 'Seb McKinnon', 'Alexandra Douglass', 'Natalia P. Gutiérrez', 'Karla Ortiz', 'Yigit Koroglu', 'Johannes Voss', 'Sam Burley', 'Cris Griffin', 'Emily Hare', 'Titus Lunter', 'Cynthia Sheppard', 'Darek Zabrocki', 'Alexandra Semushina']

artists = [
    "Alexandre Cabanel",
    "Don Bluth",
    "Doug Chiang",
    "Ridley Scott",
    "Satoshi Kon",
    "Platon",
    "Robert Capa",
    "Rodrigo Prieto",
    "Sebastiaõ Salgado",
    "Steve McCurry",
    "Alphonso Mucha",
    "Ernst Haeckel",
    "Gerhard Munthe",
    "Gustav Klimt",
    "Henri de Toulouse-Lautrec",
    "Ivan Bilibin",
    "Kaethe Butcher",
    "Kay Nielsen",
    "Lawren Harris",
    "Louis Comfort Tiffany",
    "Margaret Macdonald Mackintosh",
    "Walter Crane",
    "Carl Larsson",
    "Harry Clarke",
    "Tom Thomson",
    "William Morris",
    "Dave Gibbons",
    "Dave McKean",
    "Dustin Nguyen",
    "Enki Bilal",
    "Farel Dalymple",
    "Frank Miller",
    "Garry Trudeau",
    "Gary Larson",
    "Geof Darrow",
    "Glenn Fabry",
    "Go Nagai",
    "Hal Foster",
    "Hirohiko Araki",
    "Hiromu Arakawa",
    "Jack Davis",
    "Jack Kirby",
    "Jamie Hewlett",
    "Jean Giraud",
    "Jeff Lemire",
    "Jeffrey Smith",
    "Jim Lee",
    "Jim Steranko",
    "John Romita Jr",
    "Junji Ito",
    "Akihiko Yoshida",
    "Annibale Carracci",
    "Anthony van Dyck",
    "Artemisia Gentileschi",
    "Caravaggio",
    "Claude Lorrain",
    "Diego VelÃ¡zquez",
    "Jan van Goyen",
    "Johannes Vermeer",
    "Kehinde Wiley",
    "Le caravaggesque",
    "Otto Marseus van Schrieck",
    "Peter Paul Rubens",
    "Pieter Claesz",
    "Roberto Ferri",
    "William Hogarth",
    "Anna Dittmann",
    "Ken Sugimori",
    "Kentaro Miura",
    "Kim Jung Gi",
    "Leiji Matsumoto",
    "Mark Brooks",
    "Masamune Shirow",
    "Matt Groening",
    "Maurice Sendak",
    "Michael Deforge",
    "Mike Mignola",
    "M.W. Kaluta",
    "Peter Bagge",
    "Phil Foglio",
    "Quentin Blake",
    "Raymond Briggs",
    "Robert Crumb",
    "Shotaro Ishinomori",
    "Simon Bisley",
    "Steve Dillon",
    "Steve Ditko",
    "TaiyÅ Matsumoto",
    "Takehiko Inoue",
    "Todd McFarlane",
    "Tsutomu Nihei",
    "Alan Lee",
    "Aleksi Briclot",
    "Alexander Jansson",
    "Anne Stokes",
    "Anton Otto",
    "Apollonia Saintclair",
    "Art Spiegelman",
    "Asaf Hanuka",
    "Ashley Wood",
    "Bernie Wrightson",
    "Brian Despain",
    "Brian Kesinger",
    "Carne Griffiths",
    "Charles Blackman",
    "Clyde Caldwell",
    "Coby Whitmore",
    "Coles Phillips",
    "Conrad Roset",
    "Dan Mumford",
    "David B. Mattingly",
    "Dorothy Lathrop",
    "Dr. Seuss",
    "Earl Norem",
    "Ed Binkley",
    "Elsa Beskow",
    "Eric Lacombe",
    "Eyvin Earle",
    "Franklin Booth",
    "Frank Schoonover",
    "Gediminas Pranckevicius",
    "Gerald Brom",
    "Heinrich Kley",
    "Ian McQue",
    "Ian Miller",
    "Igor Morski",
    "Jack Butler Yeats",
    "Gerhard Richter",
    "H. R. Giger",
    "Jean-Michel Basquiat",
    "Jeff Koons",
    "Kent Monkman",
    "Mat Collishaw",
    "Odd Nerdrum",
    "Hokusai",
    "Ansel Adams",
    "Carl Holsoe",
    "Tove Jansson",
    "Edmund Leighton",
    "Affadi",
    "Alexej von Jawlensky",
    "Alfred Kubin",
    "Alice Neel",
    "Arshile Gorky",
    "Beeple",
    "Bernard Buffet",
    "Chaim Soutine",
    "Cuno Amiet",
    "Ed Emshwiller",
    "Egon Schiele",
    "Elain de Kooning",
    "Erich Heckel",
    "Erich Ludwig Kirchner",
    "Francis Bacon",
    "Frits Van den Berghe",
    "Georges Rouault",
    "Harold Elliott",
    "Irma Stern",
    "James Ensor",
    "Karl Schmidt-Rottluff",
    "Lyonel Feininger",
    "Marco Mazzoni",
    "Marianne von Werefkin",
    "Mark Rothko",
    "Max Beckmann",
    "Oskar Kokoschka",
    "Otto Dix",
    "Paul Klee",
    "Wassily Kandinsky",
    "Caspar David Friedrich",
    "Jean Leon Gerome",
    "H.R. Giger",
    "Tomer Hanuka",
    "Van Herpen",
    "Al Hirschfeld",
    "Damien Hirst",
    "David Burliuk",
    "Joseph Stella",
    "Albrecht Durer",
    "Shiki",
    "Takato Yamamoto",
    "James Jean",
    "Jasmine Becket-Griffith",
    "Jason Edmiston",
    "J.C. Leyendecker",
    "Jesper Ejsing",
    "J. J. Grandville",
    "John Bauer",
    "John Kenn Mortensen",
    "John Philip Falter",
    "Justin Gerard",
    "Kaja Foglio",
    "Kate Greenaway",
    "Laurie Greasley",
    "Laurie Lipton",
    "Lee Madgwick",
    "Louis Wain",
    "Luis Royo",
    "Marc Simonetti",
    "Maxfield Parrish",
    "Mike Winkelmann",
    "Milton Glaser",
    "Noriyoshi Ohrai",
    "Pascal Campion",
    "Paul Rand",
    "Ralph McQuarrie",
    "Randolph Caldecott",
    "Raymond Swanland",
    "Rebecca Guay",
    "Richard Corben",
    "Richard Doyle",
    "Richard Scarry",
    "Rockwell Kent",
    "Roger Dean",
    "Russ Mills",
    "Sam Bosma",
    "Sam Guay",
    "Sergio Toppi",
    "Sidney Prior Hall",
    "Stanley Donwood",
    "Stephanie Law",
    "Stephen Gammell",
    "Steve Argyle",
    "Tatsuro Kiuchi",
    "Ted Nasmith",
    "Tim Doyle",
    "Tom Lovell",
    "Tony DiTerlizzi",
    "William Stout",
    "Yoshitaka Amano",
    "Yuumei",
    "Makoto Shinkai",
    "Mary Blair",
    "Tex Avery",
    "Ub Iwerks",
    "Jeff Easley",
    "Kuang Hong",
    "Larry Elmore",
    "Raphael Lacoste",
    "Bob Byerley",
    "Carl Holsøe",
    "Codex Seraphinianus",
    "Alberto Giacometti",
    "Alexander Milne Calder",
    "Dave Chihuly",
    "Ellen Jewett",
    "Emil Melmoth",
    "Fernando Botero",
    "Gustav Vigeland",
    "Hope Gangloff",
    "Jason Limon",
    "Jeremy Mann",
    "Josephine Wall",
    "Matti Suuronen",
    "Rudolf Hausner",
    "Santiago Caruso",
    "Zdzislaw Beksinski",
    "Bjarke Ingels",
    "Frank Lloyd Wright",
    "Hugh Ferriss",
    "Luc Schuiten",
    "Zaha Hadid",
    "Anne Geddes",
    "Claude Cahun",
    "Diane Arbus",
    "Elliott Erwitt",
    "Gregory Crewdson",
    "Hendrik Kerstens",
    "Hugh Kretschmer",
    "Liam Wong",
    "Nick Knight",
    "Nobuyoshi Araki",
    "Sally Mann",
    "Stefan Gesell",
    "Anne McCaffrey",
    "H.P. Lovecraft",
    "Storm Thorgerson",
    "Camille Corot",
    "Camille Pissarro",
    "Childe Hassam",
    "Claude Monet",
    "Frederick Lord Leighton",
    "Harriet Backer",
    "Henri Matisse",
    "Impressionist",
    "Isaac Levitan",
    "John Singer Sargent",
    "Leonid Afremov",
    "Lovis Corinth",
    "Malcolm Liepke",
    "Paula Modersohn-Becker",
    "Paul CÃ©zanne",
    "Vilhelm Hammershoi",
    "Chiharu Shiota",
    "Dan Flavin",
    "James Turrell",
    "Ed Mell",
    "Guido Borelli da Caluso",
    "John Atkinson Grimshaw",
    "John Perceval",
    "Neil Welliver",
    "Esao Andrews",
    "Mark Ryden",
    "Robert Williams",
    "Ryohei Hase",
    "Albert Bierstadt",
    "JoaquÃ­n Sorolla",
    "John Frederick Kensett",
    "Martin Johnson Heade",
    "El Greco",
    "Giuseppe Arcimboldo",
    "J. C. Leyendecker",
    "Joseph Ducreux",
    "William Henry Hunt",
    "Benoit B. Mandelbrot",
    "Agnes Lawrence",
    "Amedeo Modigliani",
    "Arthur Dove",
    "Beauford Delaney",
    "Candido Portinari",
    "Emil Nolde",
    "Frank Auerbach",
    "Friedensreich Regentag Dunkelbunt Hundertwasser",
    "George Grosz",
    "Georgia O’Keeffe",
    "Hannah Hoch",
    "Howard Hodgkin",
    "Hundertwasser",
    "Jackson Pollock",
    "James Abbott McNeill Whistler",
    "Joan Miro",
    "John Harris",
    "John Hoyland",
    "Joseph Cornell",
    "Karl Blossfeldt",
    "Kazimir Malevich",
    "Laurel Burch",
    "Lucian Freud",
    "Lyubov Popova",
    "Marsden Hartley",
    "Max Beckmann",
    "M.C. Escher",
    "Mikhail Vrubel",
    "Milton Avery",
    "Natalia Goncharova",
    "Norman Rockwell",
    "Pablo Picasso",
    "Patrick Heron",
    "Paul Gauguin",
    "Philip Guston",
    "Pierre-Auguste Renoir",
    "Piet Mondrian",
    "Robert Motherwell",
    "Roberto Matta",
    "Rufino Tamayo",
    "Ryan Hewett",
    "Sonia Delaunay",
    "Stuart Davis",
    "Victor Vasarely",
    "William S Burroughs",
    "Yaacov Agam",
    "Yves Klein",
    "Anton Fadeev",
    "John James Audubon",
    "Maria Sibylla Merian",
    "Richard Dadd",
    "Rob Liefeld",
    "Alex Maleev",
    "Alphonse Mucha",
    "Craig Mullins",
    "Victo Ngai",
    "Georgia O’Keefe",
    "Pixar",
    "Bill Plympton",
    "Greg Rutkowsk",
    "Theodor Seuss Geisel",
    "E.H. Shepard",
    "Ralph Steadman",
    "Mario Testino",
    "Albert Uderzo",
    "Tillie Walden",
    "John William Waterhouse",
    "Brandon Woelfel",
    "Wong Kar-Wai",
    "Anders Zorn",
    "Vilmos Zsigmond",
    "Weegee",
    "Annie Leibovitz",
    "Edwin Austen Abbey",
    "Wes Anderson",
    "Balthus",
    "Barry Blitt",
    "Sylvain Chomet",
    "John Kricfalusi (a.k.a. John K)",
    "Austin Briggs",
    "Ramón Casas",
    "Grzegorz Domaradzki",
    "Cindy Sherman",
    "Gottfried Helnwein",
    "Jeremy Geddes",
    "Alberto Vargas",
    "Andy Warhol",
    "David Hockney",
    "Hiroshi Nagai",
    "Jim Fitzpatrick",
    "Karol Bak",
    "Kelly McKernan",
    "Lisa Frank",
    "Mab Graves",
    "Peter Max",
    "Robert Rauschenberg",
    "Roy Lichtenstein",
    "Takashi Murakami",
    "Tomokazu Matsuyama",
    "Pierre Bonnard",
    "Ã‰mile Bernard",
    "Georges Seurat",
    "Henri-Edmond Cross",
    "Henri Rousseau",
    "Jean Metzinger",
    "Tivadar CsontvÃ¡ry Kosztka",
    "Vincent van Gogh",
    "Alex Grey",
    "Alyssa Monks",
    "Arnold BÃ¶cklin",
    "Evelyn De Morgan",
    "Franz Sedlacek",
    "Gaston Bussiere",
    "George Frederic Watts",
    "Gustave Moreau",
    "Jean Delville",
    "John Duncan",
    "Marcell Chagall",
    "Martiros Saryan",
    "Nicholas Roerich",
    "Odilon Redon",
    "Viktor Vasnetsov",
    "Asher Brown Durand",
    "George Inness",
    "Thomas Cole",
    "Hiroshi Yoshida",
    "Katsushika Hokusai",
    "Charles E. Burchfield",
    "Howard Finster",
    "Beatrix Potter",
    "Abigail Larson",
    "Shinji Aramaki",
    "Tim Burton",
    "Zack Snyder",
    "Charles Eames",
    "Canaletto",
    "Akihiko Yoshida",
    "Akihito Tsukushi",
    "Aaron Douglas",
    "Nao emoto",
    "Hieronymus Bosch",
    "Hubert Robert",
    "Leonardo da Vinci",
    "Matthias GrÃ¼newald",
    "Michaelangelo",
    "Pieter Bruegel the Elder",
    "Raphael",
    "Sandro Botticelli",
    "Andreas Rocha",
    "Artgerm",
    "Arthur Rackham",
    "Atey Ghailan",
    "Brandon Woelfel",
    "Cicely Mary Barker",
    "Daido Moriyama",
    "Dante Rossetti",
    "Dean Cornwell",
    "Eddie Mendoza",
    "Edmund Dulac",
    "edouard bisson",
    "Eugene Boudin",
    "Finnian MacManus",
    "Hayao Miyazaki",
    "Henry Scott Tuke",
    "Ilya Kuvshinov",
    "Ilya Repim",
    "J. C. Leyendecker",
    "James Gurney",
    "Jerry Pinkney",
    "Joaquín Sorolla",
    "John Howe",
    "John Totleben",
    "Kim Keever",
    "Marc Silvestri",
    "Michelangelo",
    "Miho Harano",
    "Mikko Lagerstedt",
    "Peter Lindbergh",
    "Peter Mohrbacher",
    "Posuka Demizu",
    "Pre-Raphaelite Brotherhood",
    "Rembrandt van Rijn",
    "Richard Avedon",
    "Roger Deakins",
    "Ruan Jia",
    "Rumiko Takahashi",
    "Shinsui Ito",
    "Simon Stålenhag",
    "Stefan Koidl",
    "Studio Ghibli",
    "Sui Ishida",
    "Swoon",
    "Tasha Tudor",
    "Theodore Robinson",
    "Tintoretto",
    "Titian",
    "WLOP",
    "Yanjun Cheng",
    "Yoji Shinkawa",
    "Yoshiyuki Tomino",
    "Zhelong Xu",
    "Alena Aenami",
    "Annton Fadeevi",
    "Charlie Bowater",
    "Christopher Balaskas",
    "Cory Loftis",
    "Craola",
    "Fenghua Zhong",
    "Greg Rutkowski",
    "Hong SoonSang",
    "Ismail Inceoglu",
    "Jordan Grimmer",
    "Krenz Cushart",
    "Michal Lisowski",
    "Noah Bradley",
    "Pascal Blanché",
    "Paul Lehr",
    "RHADS",
    "Ross Tran",
    "Tyler Edlin",
    "Victor Adame Minguez",
    "Akari Toriyama",
    "Al Williamson",
    "Angus McKie",
    "Anton Pieck",
    "Ben Templesmith",
    "Brian Bolland",
    "Carl Barks",
    "Charles M. Schulz",
    "Craig Davison",
    "Dave Dorman"]
